Repository radical-cybertools/radical.saga, pull requests merged in 2020-08, with the labels that each got.

#803 Remove redis-adaptor loading
  src/radical/saga/configs/registry_default.json
Labels: priority:medium, topic:api, type:bug

#804 fix threading model for redis adaptor
  examples/master_worker/master.py
  examples/master_worker/worker.py
  examples/tutorial/saga_example_remote.py
  examples/tutorial/saga_example_remote_cluster_staging.py
  examples/tutorial/saga_example_remote_staging.py
  src/radical/saga/adaptors/redis/redis_1.py
  src/radical/saga/adaptors/redis/redis_2.py
  src/radical/saga/adaptors/redis/redis_cache.py
  src/radical/saga/adaptors/redis/redis_namespace.py
  src/radical/saga/adaptors/redis/redis_ordered_dict.py
Labels: priority:low, topic:api, type:bug

#805 "fix" container add
  docs/source/usage/install.rst
  examples/jobs/localjobcontainer.py
  examples/master_worker/master.py
  examples/master_worker/worker.py
  examples/tutorial/saga_example_remote.py
  examples/tutorial/saga_example_remote_cluster_staging.py
  examples/tutorial/saga_example_remote_staging.py
  src/radical/saga/adaptors/redis/redis_1.py
  src/radical/saga/adaptors/redis/redis_2.py
  src/radical/saga/adaptors/redis/redis_cache.py
  src/radical/saga/adaptors/redis/redis_namespace.py
  src/radical/saga/adaptors/redis/redis_ordered_dict.py
  src/radical/saga/configs/registry_default.json
  src/radical/saga/task.py
Labels: comp:engine, priority:critical, topic:python3, type:bug

#806 Job description attribute SystemArchitecture
  docs/source/library/job/index.rst
  src/radical/saga/adaptors/lsf/lsfjob.py
  src/radical/saga/adaptors/slurm/slurm_job.py
  src/radical/saga/job/constants.py
  src/radical/saga/job/description.py
  tests/adaptors/lsf/test_lsf_adaptor.py
Labels: comp:lsf, comp:slurm, priority:medium, topic:execution, type:feature

#808 Key `options` for JD attribute SystemArchitecture (LSF)
  src/radical/saga/adaptors/lsf/lsfjob.py
  tests/adaptors/lsf/test_lsf_adaptor.py
Labels: comp:lsf, priority:medium, topic:resouce:summit, type:enhancement
