Repository radical-cybertools/radical.saga, pull requests merged in 2020-06, with the labels that each got.

#781 re-introduce shell wrapper timeout
  src/radical/saga/adaptors/shell/shell_wrapper.sh
Labels: comp:shell_job, priority:critical, topic:termination, type:bug

#789 typo
  examples/tutorial/mandelbrot/saga_mandelbrot.py
Labels: priority:medium, type:bug, type:documentation

#790 type error fix
  examples/tutorial/mandelbrot/saga_mandelbrot.py
Labels: priority:medium, type:bug, type:documentation

#788 replace PIL with Pillow
  docs/source/tutorial/part5.rst
Labels: priority:low, topic:deployment, type:documentation
