Repository radical-cybertools/radical.saga, pull requests merged in 2021-05, with the labels that each got.

#826 fix python binary name
  setup.py
Labels: priority:critical, topic:deployment, type:bug

#828 No linting for SAGA?
  .github/workflows/python-app.yml
Labels: priority:medium

#827 Cobalt script option `--attrs`
  src/radical/saga/adaptors/cobalt/cobaltjob.py
  tests/adaptors/test_cobalt.py
Labels: comp:cobalt, priority:medium, topic:execution, type:feature
