Repository radical-cybertools/radical.saga, pull requests merged in 2022-12, with the labels that each got.

#859 bump python test env to 3.7
  .github/workflows/python-app.yml
Labels: layer:rct, priority:high, topic:testing, type:refactor

#860 fix docs
  docs/source/conf.py
  requirements-docs.txt
  requirements-tests.txt
  requirements.txt
  setup.py
Labels: priority:high, type:documentation

#861 sync with ru
  .readthedocs.yml
  LICENSE.md
Labels: type:documentation

#863 enhance SMT control in Slurm adaptor
  src/radical/saga/adaptors/slurm/slurm_job.py
  tests/adaptors/test_slurm.py
Labels: comp:slurm, priority:medium, topic:enhancement

#864 ensure requirements are added to sdist
  MANIFEST.in
Labels: priority:high, type:bug, topic:deployment

#865 updated and cleaned PBSPro adapter
  src/radical/saga/adaptors/pbspro/pbsprojob.py
  tests/adaptors/test_pbspro.py
Labels: comp:pbs, priority:medium, type:enhancement, topic:enhancement
