Repository radical-cybertools/radical.saga, pull requests merged in 2022-02, with the labels that each got.

#841 consistent use of radical_base
  examples/context/context_ssh.py
  src/radical/saga/adaptors/cobalt/cobaltjob.py
  src/radical/saga/adaptors/context/myproxy.py
  src/radical/saga/adaptors/loadl/loadljob.py
  src/radical/saga/adaptors/sge/sgejob.py
  src/radical/saga/adaptors/shell/shell_job.py
  src/radical/saga/adaptors/shell/shell_wrapper.sh
  src/radical/saga/configs/adaptors_cobaltjob.json
  src/radical/saga/configs/adaptors_myproxy.json
  src/radical/saga/configs/adaptors_sgejob.json
  src/radical/saga/configs/adaptors_shell_job.json
  src/radical/saga/utils/pty_shell.py
Labels: priority:high, topic:execution, topic:resource, type:bug

#842 CI: use RCT devel packages
  .github/workflows/python-app.yml
Labels: priority:medium, topic:testing

#843 fix dep versions
  setup.py
Labels: priority:medium, topic:deployment
